#! /bin/bash

TARGET=$1
CURR_DIR=$(pwd)
STRING="${CURR_DIR:1}"

IFS='/'

read -A array <<< "${STRING}"
LENGTH=${#array[*]}
COUNT=0

for (( i=1; i<${LENGTH}+1; i++ ))
 do
  if [ ${TARGET} = ${array[i]} ]
   then break
  else
   let "COUNT++"
  fi 
done

let BACK_TO=${LENGTH}-1-${COUNT}

for (( i=0; i<${BACK_TO}; i++ ))
 do 
  cd ../
done

