#! /bin/bash


#There is a big problem with multiplcation. When * is entered in as a argument to the cacl command the * means all the folders in the current directory 

join() {
  local IFS=""
  CALC="$*"
}

#Splitting string into an array of strings
splitString(){
    read -a ARRAY <<< "$*"
}

#Calling splitString and passing it the entire line argument
splitString $* 

LENGTH=${#ARRAY[*]}

if [ ${ARRAY[0]} = "-p" ] 
    then PRECISION=${ARRAY[1]}
    #Slicing array and passing it to join function 
    join ${ARRAY[@]:2:${LENGTH}-1}
else 
    PRECISION=5
    join ${ARRAY[*]}
fi 

#Passing the CALC string to the BC enviornment to do calculations 
bc << _EOF_
scale=${PRECISION}
${CALC}
_EOF_

