#! /bin/bash

FILE_NAME=$1
MAX_LENGTH=0
MAX_WORD=""

if [ -r ${FILE_NAME} ]; then
    FILE_CONTENT=$(strings ${FILE_NAME})
    for word in ${FILE_CONTENT}; 
    do
        if [ ${#word} -gt ${MAX_LENGTH} ]; then
            MAX_LENGTH=${#word}
            MAX_WORD=${word}
        fi
    done
else echo "No such file or directory"
fi

echo ""
echo Word: ${MAX_WORD}
echo Length: ${MAX_LENGTH}
echo ""
