#! /bin/bash

LOCATION=$1
PROJECT_NAME=$2

HTMLTEXT='<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="./index.js" defer type='module'></script>
    <link rel="stylesheet" href="./styles.css" />
    <title>ProjectName</title>
  </head>
  <body>
  </body>
</html>
'

mkdir ${LOCATION}/${PROJECT_NAME} && cd ${LOCATION}/${PROJECT_NAME}
echo ${HTMLTEXT} >> index.html
touch index.js styles.css

echo " "
echo "Vanilla JS Project Created"
echo "Location: ${LOCATION}"
echo "Project Name: ${PROJECT_NAME}"
echo " "